project:
  type: website
website:
  title: "11130826"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto  # re-render only when source changes



